# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-15 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bihin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bihin_no', models.CharField(help_text='<small><small>ex.) JSL.NT.123456</small></small>', max_length=255, unique=True, verbose_name='管理No')),
                ('bihin_type', models.IntegerField(choices=[(0, 'ノートパソコン'), (1, 'デスクトップパソコン')], verbose_name='種別')),
                ('bihin_ipaddr', models.CharField(blank=True, max_length=255, verbose_name='IPアドレス')),
                ('bihin_manufct', models.CharField(help_text='<small><small>ex.) Apple/DELL/lenovo</small></small>', max_length=255, verbose_name='メーカー')),
                ('bihin_os', models.CharField(max_length=255, verbose_name='OS')),
                ('bihin_cpu', models.CharField(max_length=255, verbose_name='CPU')),
                ('bihin_hdd', models.CharField(max_length=255, verbose_name='HDD容量')),
                ('bihin_mem', models.CharField(max_length=255, verbose_name='メモリ')),
                ('bihin_mediadrv', models.CharField(blank=True, max_length=255, verbose_name='メディアドライブ')),
                ('bihin_shisan', models.IntegerField(choices=[(0, '購入品'), (1, 'リース')], verbose_name='資産')),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispsize', models.CharField(blank=True, max_length=255, verbose_name='付属品：ディスプレイ(size)')),
                ('dispno', models.CharField(blank=True, max_length=255, unique=True, verbose_name='付属品：ディスプレイ(管理No)')),
                ('bihin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='bihin.Bihin', verbose_name='機器(Display)')),
            ],
        ),
        migrations.CreateModel(
            name='Keybord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keybordno', models.CharField(blank=True, max_length=255, unique=True, verbose_name='付属品：キーボード(管理No)')),
                ('bihin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard', to='bihin.Bihin', verbose_name='機器(Keyboard)')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_date', models.DateField(blank=True, help_text='<small><small>ex.) 2016-09-12</small></small>', null=True, verbose_name='リース期限日')),
                ('bihin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='bihin.Bihin', verbose_name='リース情報')),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouseno', models.CharField(blank=True, max_length=255, unique=True, verbose_name='付属品：マウス(管理No)')),
                ('bihin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse', to='bihin.Bihin', verbose_name='機器(Mouse)')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='使用者')),
                ('prj', models.CharField(blank=True, max_length=255, verbose_name='使用プロジェクト')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='保管場所')),
                ('bihin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='bihin.Bihin', verbose_name='使用者情報')),
            ],
        ),
    ]
