# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-29 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0004_bihin_bihin_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bihin',
            name='bihin_text',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
    ]
