# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-01 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0005_auto_20170129_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='lease_date',
            field=models.DateField(help_text='<small><small>ex.) 2016-09-12</small></small>', null=True, verbose_name='リース期限日'),
        ),
    ]
